### ISSUE TITLE
Create GitHub organization and transfer repo there

### ISSUE THREAD

**Issue by lwjohnst86** [NetCoupler/NetCoupler#42]
I might be able to get some research assistant help working on this project. Given that there may be three people working on this, I think it would be easier collaboration to create an organization and have the development of NetCoupler happen over there rather than through your account. Things like running Travis CI (for testing), building the (eventual) website, etc would just be so much easier if the repo was in an organization.

We can discuss when we meet.

**Comment by lwjohnst86** [comment]
@ClemensWittenbecher Can you move this repo over to https://github.com/NetCoupler? You can do that via "Settings" at the bottom it says "Transfer Repo". It will be much easier if we work through an organization account.

(Also, the worker I was going to hire unfortunately had to pull out at the last minute due to overtime work at her new job... sad times).

**Comment by ClemensWittenbecher** [comment]
Hi.

Okay, I transfered it. Hope everything was correct - I am a bit nervous because the transfer  button was in the danger zone ;-)


>>> Luke W Johnston <notifications@github.com> 9/10/2019 1:51 pm >>>
@ClemensWittenbecher Can you move this repo over to https://github.com/NetCoupler? You can do that via "Settings" at the bottom it says "Transfer Repo". It will be much easier if we work through an organization account.

(Also, the worker I was going to hire unfortunately had to pull out at the last minute due to overtime work at her new job... sad times).

**Comment by lwjohnst86** [comment]
Amazing! Great thanks! :grin:

**Comment by ClemensWittenbecher** [comment]
I pulled and solved a couple of conflicts. Should I push the updates now? 


>>> Luke W Johnston <notifications@github.com> 9/10/2019 2:59 pm >>>
Closed #42.

-- 
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub:
https://github.com/NetCoupler/NetCoupler/issues/42#event-2623345260

**Comment by lwjohnst86** [comment]
Yes, that should be fine :)
